# Generated by Django 4.2.16 on 2025-01-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
    ]
